services:
  - type: web
    name: my-php-app
    runtime: docker
    dockerfilePath: Dockerfile  # Points to your Dockerfile
    envVars:
      - key: PORT
        value: 80  # Apache runs on 80 by default